apiVersion: v1
kind: Service
metadata:
  name: fastify-ts-esm-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
  selector:
    app: fastify-ts-esm
    type: backend
